### ISSUE TITLE
Update how caching works for CI

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/lighthouse-plugin-greenhouse#12]
Right now, when we use Travis CI, I think that because it caches some calls like ones to `npm install`, we end up with the build failing, in this example see build #22:

https://travis-ci.org/thegreenwebfoundation/lighthouse-plugin-greenhouse/builds/569455160

However, the same build passes when you clear the cache and run it - we end up with it passing the tests.

I think this is result of the caching causing an error like so:

```
npm WARN checkPermissions Missing write access to /home/travis/build/thegreenwebfoundation/lighthouse-plugin-greenhouse/node_modules/lighthouse-plugin-greenhouse

npm WARN lighthouse-plugin-greenhouse@0.0.2 No repository field.

npm ERR! path /home/travis/build/thegreenwebfoundation/lighthouse-plugin-greenhouse/node_modules/lighthouse-plugin-greenhouse

npm ERR! code ENOENT

npm ERR! errno -2

npm ERR! syscall access

npm ERR! enoent ENOENT: no such file or directory, access '/home/travis/build/thegreenwebfoundation/lighthouse-plugin-greenhouse/node_modules/lighthouse-plugin-greenhouse'

npm ERR! enoent This is related to npm not being able to find a file.

npm ERR! enoent 

npm ERR! A complete log of this run can be found in:

npm ERR!     /home/travis/.npm/_logs/2019-08-11T13_31_49_335Z-debug.log

```

It looks we can disable the cache to at least give us reliable build info, by adding this  to TravisCI:

```
cache: false
```

That will result in more data being shifted around, which is less than ideal.

Weirdly, the travis config file we have on this repo is pretty much the same as the one used by the [lighthouse-plugin-field-performance][lpfp] plugin,  which this greenhouse plugin is largely based on, and it looks like their builds are passing fine.

It might be worth asking @alekseykulikov, to see if he had a similar issue for his plugin, to compare notes.

[lpfp]: https://github.com/treosh/lighthouse-plugin-field-performance/blob/master/.travis.yml
https://docs.travis-ci.com/user/caching/

**Comment by PragTob** [comment]
:wave: 

Are you sure this is caching related? Doesn't look like that to me... maybe some flakiness on travis' side? Was the problem always there or just recently?

I'd say set cache:

```
cache:
  npm: false
```

And if it goes away you're at least sure it's cache related. If it stays you also now more.

Overall, it's sad for travis that you'll take longer but the impact shouldn't be _that_ big :)

Cheers and hope I was helpful,
Tobi

**Comment by mrchrisadams** [comment]
Sounds worth a try, if nothing else 👍 .

Danke!

**Comment by mrchrisadams** [comment]
It looks like it worked! WOOHOO, thanks @PragTob!

(gonna try out a thing)

@all-contributors please add @PragTob  for CI wrangling tips

**Comment by mrchrisadams** [comment]
Ooops. Let's try this again:

@all-contributors please add @PragTob for helping sort out infra with CI wrangling tips
